app.py
#!/usr/bin/env python

# Copyright 2018 Julian Tu

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os

import mistune
from flask import Flask, render_template
from flask_socketio import SocketIO, emit

from engine import Game
from views.game_view import game_view

SITE_ROOT = os.path.realpath(os.path.dirname(__file__))
app = Flask(__name__)
app.register_blueprint(game_view, url_prefix='/play')
socketio = SocketIO(app)
game = Game()


@app.route('/')
def index():
    with open(os.path.join(SITE_ROOT, 'static', 'index.md')) as f:
        body_text = mistune.markdown(f.read(), escape=False)
    return render_template('index.html', body_text=body_text)


@socketio.on('get_unused_id')
def handle_get_unused_id():
    return game.get_unused_player_id()


@socketio.on('join')
def handle_join(player_id):
    app.logger.info('got join for ' + player_id)
    game.add_player(player_id)
    emit('should_update', broadcast=True)


@socketio.on('exit')
def handle_exit(player_id):
    game.delete_player(player_id)
    emit('should_update', broadcast=True)


@socketio.on('restart')
def handle_restart():
    global game
    app.logger.info('got restart')
    game = Game()
    emit('restart_ack', broadcast=True)


@socketio.on('request_info')
def handle_request_info(player_id):
    app.logger.info('got request_info for: {}'.format(player_id))
    return {
        'cash': game.get_cash(player_id),
        'boats': game.get_boats(player_id),
        'pots': game.get_pots(player_id),
        'day': game.day,
        'consecutive_bad': game.consecutive_bad,
        'yesterday_weather': game.yesterday_weather,
        'day_num': game.day_num,
    }


@socketio.on('request_ranking')
def handle_request_ranking():
    ranking = []
    for player_id in game.player_ids:
        ranking.append({
            'id': player_id,
            'cash': game.get_cash(player_id),
            'submitted': game.did_submit(player_id),
        })
    ranking.sort(key=lambda rank: int(rank['cash']), reverse=True)

    # assign a ranking with ties
    previous_cash = float('inf')
    rank = 0
    for entry in ranking:
        if entry['cash'] != previous_cash:
            rank += 1
        entry['rank'] = rank
        previous_cash = entry['cash']
    return ranking


@socketio.on('buy_boat')
def handle_buy_boat(player_id):
    if not game.buy_boat(player_id):
        return game.cash_needed_for_boat(player_id)
    game.delete_strategy(player_id)
    return 0


@socketio.on('sell_boat')
def handle_sell_boat(player_id):
    # deletes the strategy if the sell is successful
    return game.sell_boat(player_id) and game.delete_strategy(player_id)


@socketio.on('submit_strategy')
def handle_submit_strategy(player_id, strategy):
    app.logger.info('submitting {} for {}'.format(strategy, player_id))
    if 'hotel_work' in strategy:
        ret = game.submit_hotel_strategy(player_id)
    else:
        ret = game.submit_fish_strategy(player_id,
                                        strategy['inshore'],
                                        strategy['offshore'])
    if ret:
        emit('should_update', broadcast=True)
    return ret


@socketio.on('next_turn')
def handle_next_turn():
    app.logger.info('attempting to advance turn...')
    if game.ready_to_finish():
        game.finish_day()
        emit('next_turn_ack', broadcast=True)
        app.logger.info('success')


@socketio.on('message')
def handle_message(message):
    app.logger.info(message)


if __name__ == '__main__':
    socketio.run(app)

engine/__init__.py
# Copyright 2018 Julian Tu

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from .Game import Game
from .Player import Player

views/game_view.py
# Copyright 2018 Julian Tu

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from flask import Blueprint, render_template

game_view = Blueprint('game_view', __name__)


@game_view.route('game')
def game():
    return render_template('game.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
	 crossorigin="anonymous">
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>
		{% block title %}L3BobsT3r G@mu-desu{% endblock title %}
	</title>
	{% block head %} {% endblock head %}
</head>

<body>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
	 crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
	 crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
	 crossorigin="anonymous"></script> {% block js %}{% endblock js %}

	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<a class="navbar-brand" href="/">Information</a>
		<a class="navbar-text" href="{{ url_for('game_view.game') }}">Lobster Game</a>
	</nav>
	<div class="container">
		{% block body %}
		<h1 class="mt-3 mb-3">Play da gaem</h1>
		{% endblock body %}
	</div>
</body>

</html>

templates/game.html
{% extends "base.html" %} {% block body %}
<script type="text/javascript" src="{{ url_for('static', filename='game.js') }}" charset="utf-8"></script>
<h1 class="text-center">Playing Lobstah "Game"</h1>

<div>
	<h2 class="mb-3">My Information</h2>
	<div class="row mb-2">
		<div class="col">
			Day <strong id="day_num">0</strong> of this torture
		</div>
		<div class="col">
			Today is: <strong id="day_of_week">Monday</strong>
		</div>
		<div class="col">
			Yesterday's weather: <strong id="yesterday_weather">Good</strong>
		</div>
		<div class="col">
			Consecutive bad weather: <strong id="consecutive_bad_weather">0</strong>
		</div>
	</div>
	<table class="table">
		<thead>
			<tr>
				<th scope="col">ID</th>
				<th scope="col">Cash</th>
				<th scope="col">Boats</th>
				<th scope="col">Pots</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td id="my_id">-</td>
				<td id="my_cash">$ -</td>
				<td id="my_boats">-</td>
				<td id="my_pots">-</td>
			</tr>
		</tbody>
	</table>
</div>

<div class="mb-3">
	<h2 class="mb-2">Planning</h2>
	<div class="form-check form-check-inline">
		<input class="form-check-input" type="radio" name="work_choice" id="hotel_radio" onclick="disableFishing()" value="hotel" checked>
		<label class="form-check-label" for="hotel_radio">
			Work at the hotel
		</label>
	</div>

	<div class="form-check form-check-inline">
		<input class="form-check-input" type="radio" name="work_choice" id="fish_radio" onclick="enableFishing()" value="fish">
		<label class="form-check-label" for="fish_radio">
			Go fish
		</label>
	</div>

	<div class="form-row mt-2">
		<div class="col">
			<label for="inshore_input">
				Pots inshore
			</label>
			<input class="form-control" type="number" min="0" id="inshore_input" value="0" disabled>
		</div>
		<div class="col">
			<label for="offshore_input">
				Pots offshore
			</label>
			<input class="form-control" type="number" min="0" id="offshore_input" value="0" disabled>
		</div>
	</div>

	<div class="mt-3">
		<div class="row">
			<div class="col">
				<button type="button" class="btn btn-primary btn-block" onclick="buyBoat()">Buy boat</button>
			</div>
			<div class="col">
				<button type="button" class="btn btn-primary btn-block" onclick="sellBoat()">Sell boat</button>
			</div>
		</div>
	</div>
	<div class="mt-2">
		<button type="button" class="btn btn-primary btn-block" id="submit_plan" onclick="submit_strategy()">Submit</button>
	</div>
</div>

<div>
	<h2>Commands</h2>
	<button type="button" class="btn btn-info" id="update-btn" onclick="updateData()">Update Information</button>
	<button type="button" class="btn btn-warning" id="next-turn-btn" onclick="nextTurn()">Next Turn</button>
	<button type="button" class="btn btn-danger" id="join-btn" onclick="join()">Join</button>
	<button type="button" class="btn btn-danger" id="leave-btn" onclick="exit()">Leave</button>
	<button type="button" class="btn btn-danger" id="restart-btn" onclick="resetGame()">Restart</button>
</div>

<div class="mt-3">
	<h2>Ranking</h2>
	<table class="table">
		<thead>
			<tr>
				<th scope="col">Rank</th>
				<th scope="col">ID</th>
				<th scope="col">Cash</th>
				<th scope="col">Strategy Submitted</th>
			</tr>
		</thead>
		<tbody id="ranking_tbody"></tbody>
	</table>
</div>
{% endblock body %} {% block js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.1.1/socket.io.slim.js" integrity="sha256-0YA7ixx4+I4GrLichcjWSQHIUSQiI8ojTDqsK7AZ5zU="
 crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js" integrity="sha256-4F7e4JsAJyLUdpP7Q8Sah866jCOhv72zU5E8lIRER4w="
 crossorigin="anonymous"></script> {% endblock js %}

templates/index.html
{% extends "base.html" %}

{% block body %}
{{ body_text|safe }}
{% endblock body %}